name: Generate Ascii

on: 
    push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout Repo
           uses: actions/checkout@v6

         - name: Install Cowsay Program
           run: sudo apt-get install cowsay -y 

         - name: Generate ASCII artwork
           run: cowsay -f dragon "run for cover, I am a dragon....RAWR">dragon.txt   

         - name: check text file exsists and show the contents
           run: |
             grep -i "dragon" dragon.txt
             cat dragon.txt
             ls -al
             
           
           
